/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Admin.Dashboard;

import Admin.Auth.AdminSession;
import Admin.Auth.LogingGuru;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Rama Dev
 */
public class Soal extends javax.swing.JFrame {

    /**
     * Creates new form Soal
     */
    public Soal(JFrame frame) {
        initComponents();
        frame.dispose();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        soal = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        dashboard = new javax.swing.JLabel();
        LogoutBtn1 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        panel_main = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        profile = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(0, 51, 153));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Logout");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel7.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 470, 80, 20));

        jLabel6.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Pengaturan");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel7.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, 150, 30));

        soal.setBackground(new java.awt.Color(255, 255, 255));
        soal.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        soal.setForeground(new java.awt.Color(255, 255, 255));
        soal.setText("Soal");
        soal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        soal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                soalMouseClicked(evt);
            }
        });
        jPanel7.add(soal, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 150, 30));

        jLabel33.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/dashboard.png"))); // NOI18N
        jLabel33.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel7.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 40, 40));

        jLabel34.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/leaderboard.png"))); // NOI18N
        jLabel34.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel7.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 30, 40));

        dashboard.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        dashboard.setForeground(new java.awt.Color(153, 153, 153));
        dashboard.setText("Dashboard");
        dashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardMouseClicked(evt);
            }
        });
        jPanel7.add(dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 150, 30));

        LogoutBtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/switch.png"))); // NOI18N
        LogoutBtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LogoutBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutBtn1MouseClicked(evt);
            }
        });
        jPanel7.add(LogoutBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, -1, -1));

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 760));

        jLabel38.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel38.setText("Halaman Soal");
        jLabel38.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, -1, -1));

        panel_main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        panel_main.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 890, 270));

        getContentPane().add(panel_main, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 890, 660));

        profile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/user.png"))); // NOI18N
        profile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        profile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profileMouseClicked(evt);
            }
        });
        getContentPane().add(profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void soalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_soalMouseClicked
        // TODO add your handling code here:
        dispose();
        Soal soal = new Soal(this);
        soal.setVisible(true);
    }//GEN-LAST:event_soalMouseClicked

    private void dashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardMouseClicked
        // TODO add your handling code here:
        dispose();
        Dashboard_Admin dashboard = new Dashboard_Admin(this, null);
        dashboard.setVisible(true);
    }//GEN-LAST:event_dashboardMouseClicked

    private void profileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileMouseClicked

    }//GEN-LAST:event_profileMouseClicked

    private void LogoutBtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutBtn1MouseClicked
        // TODO add your handling code here:
        int choice = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin logout?", "Konfirmasi Logout", JOptionPane.YES_NO_OPTION);

        if (choice == JOptionPane.YES_OPTION) {
            AdminSession.setLoggedInUser(null);

            LogingGuru loginPage = new LogingGuru(this);
            loginPage.setVisible(true);

            this.dispose();
        }
    }//GEN-LAST:event_LogoutBtn1MouseClicked

    /**
         * @param args the command line arguments
         */
        //    public static void main(String args[]) {
        //        /* Set the Nimbus look and feel */
        //        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        //        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        //         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
        //         */
        //        try {
        //            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        //                if ("Nimbus".equals(info.getName())) {
        //                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
        //                    break;
        //                }
        //            }
        //        } catch (ClassNotFoundException ex) {
        //            java.util.logging.Logger.getLogger(Soal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        //        } catch (InstantiationException ex) {
        //            java.util.logging.Logger.getLogger(Soal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        //        } catch (IllegalAccessException ex) {
        //            java.util.logging.Logger.getLogger(Soal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        //        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        //            java.util.logging.Logger.getLogger(Soal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        //        }
        //        //</editor-fold>
        //
        //        /* Create and display the form */
        //        java.awt.EventQueue.invokeLater(new Runnable() {
        //            public void run() {
        //                new Soal().setVisible(true);
        //            }
        //        });
        //    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LogoutBtn1;
    private javax.swing.JLabel dashboard;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel panel_main;
    private javax.swing.JLabel profile;
    private javax.swing.JLabel soal;
    // End of variables declaration//GEN-END:variables
}
