/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Admin.Dashboard;

import Admin.Auth.AdminSession;
import Admin.Auth.LogingGuru;
import dbConnect.dbConnect;
import static dbConnect.dbConnect.addPackage;
import static dbConnect.dbConnect.deletePackage;
import static dbConnect.dbConnect.editPackage;
import java.awt.Color;
import java.sql.Blob;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.beans.Statement;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rama Dev
 */
public class Soal extends javax.swing.JFrame {

    private String question;
    private String answer;
    private List<String> options;
    boolean success;

    String pathImgPaket = null;

    /**
     * Creates new form Soal
     *
     * @param frame frame
     */
    public Soal(JFrame frame) {
        initComponents();
        frame.dispose();
        tbload();
//        label_image_paket.setIcon(null);
        this.setVisible(true);
    }

    public void tbload() {
        DefaultTableModel dt = (DefaultTableModel) tabel_paket.getModel();
        dt.setRowCount(0);

        try (Connection connection = dbConnect.connect()) {
            if (connection != null) {
                String query = "SELECT * FROM packages";
                PreparedStatement preparedStatement = connection.prepareStatement(query);
                ResultSet rs = preparedStatement.executeQuery();

                while (rs.next()) {
                    Vector<Object> rowData = new Vector<>();
                    rowData.add(rs.getString(1));
                    rowData.add(rs.getString(2));
                    rowData.add(rs.getString(3));

                    Blob imageBlob = rs.getBlob(4);
                    String imagePath = "src/assets/paket/" + rs.getString(1) + ".png";

                    File imageFile = new File(imagePath);

                    if (imageFile.exists()) {
                        // Use existing image file to create ImageIcon
                        BufferedImage image = ImageIO.read(imageFile);
                        ImageIcon icon = new ImageIcon(image);
                        label_image_paket.setIcon(icon);
                    } else if (imageBlob != null) {
                        // Save image from Blob to file
                        try (InputStream inputStream = imageBlob.getBinaryStream(); FileOutputStream fos = new FileOutputStream(imageFile)) {
                            byte[] buffer = new byte[1024];
                            int bytesRead;
                            while ((bytesRead = inputStream.read(buffer)) != -1) {
                                fos.write(buffer, 0, bytesRead);
                            }
                        }

                        // Create ImageIcon from the saved image file
                        BufferedImage image = ImageIO.read(imageFile);
                        ImageIcon icon = new ImageIcon(image);
                        label_image_paket.setIcon(icon);
                    } else {
                        // No image found for the package, set text to "Belum ada gambar"
                        label_image_paket.setText("Belum ada gambar");
                        imagePath = "Belum ada gambar";
                    }

                    // Add imagePath to rowData
                    rowData.add(imagePath);

                    dt.addRow(rowData);
                }
            }
        } catch (SQLException | IOException e) {
            dbConnect.logger.log(Level.SEVERE, "Error loading packages", e);
        }
    }

    public Soal(String question, String answer, List<String> options) {
        this.question = question;
        this.answer = answer;
        this.options = options;
    }

    public String getQuestion() {
        return question;
    }

    public String getAnswer() {
        return answer;
    }

    public List<String> getOptions() {
        return options;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        materi_p = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        dashboard = new javax.swing.JLabel();
        LogoutBtn1 = new javax.swing.JLabel();
        soal1 = new javax.swing.JLabel();
        p_paket = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        profile = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        panel_main = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        panel_materi = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        panel_paket = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tabel_paket = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        id_paket_t = new javax.swing.JTextField();
        save_button = new javax.swing.JButton();
        update_btn_paket = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        p_search = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        nama_paket_paket1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        deskripsi_paket = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        delete_paket_btn = new javax.swing.JButton();
        upload_img_paket = new javax.swing.JButton();
        label_image_paket = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(0, 51, 153));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Logout");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel7.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 470, 80, 20));

        jLabel6.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Pengaturan");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel7.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, 150, 30));

        materi_p.setBackground(new java.awt.Color(255, 255, 255));
        materi_p.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        materi_p.setForeground(new java.awt.Color(255, 255, 255));
        materi_p.setText("Material Pembelajaran");
        materi_p.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        materi_p.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                materi_pMouseClicked(evt);
            }
        });
        jPanel7.add(materi_p, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 200, 30));

        jLabel33.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/dashboard.png"))); // NOI18N
        jLabel33.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel7.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 40, 40));

        jLabel34.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/leaderboard.png"))); // NOI18N
        jLabel34.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel7.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 30, 40));

        dashboard.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        dashboard.setForeground(new java.awt.Color(153, 153, 153));
        dashboard.setText("Dashboard");
        dashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardMouseClicked(evt);
            }
        });
        jPanel7.add(dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 150, 30));

        LogoutBtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/switch.png"))); // NOI18N
        LogoutBtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LogoutBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutBtn1MouseClicked(evt);
            }
        });
        jPanel7.add(LogoutBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, -1, -1));

        soal1.setBackground(new java.awt.Color(255, 255, 255));
        soal1.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        soal1.setForeground(new java.awt.Color(255, 255, 255));
        soal1.setText("Soal");
        soal1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        soal1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                soal1MouseClicked(evt);
            }
        });
        jPanel7.add(soal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 150, 30));

        p_paket.setBackground(new java.awt.Color(255, 255, 255));
        p_paket.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        p_paket.setForeground(new java.awt.Color(255, 255, 255));
        p_paket.setText("Paket Belajar");
        p_paket.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        p_paket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p_paketMouseClicked(evt);
            }
        });
        jPanel7.add(p_paket, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 150, 30));

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 760));

        jLabel38.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel38.setText("Halaman Guru");
        jLabel38.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, -1, -1));

        profile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/user.png"))); // NOI18N
        profile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        profile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profileMouseClicked(evt);
            }
        });
        getContentPane().add(profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 10, -1, -1));

        panel_main.setBackground(new java.awt.Color(0, 204, 0));
        panel_main.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel_main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        panel_main.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 990, 270));
        panel_main.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 230, 40));

        jLabel3.setText("Jawaban");
        panel_main.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 0, 255));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panel_main.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-32704, -32620, 75, -1));

        jButton2.setBackground(new java.awt.Color(0, 255, 255));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        panel_main.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 0, 0));

        jButton3.setBackground(new java.awt.Color(255, 0, 0));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        panel_main.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 0, 0));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panel_main.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, 240, 40));

        jLabel14.setText("Nama Paket");
        panel_main.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, -1, -1));

        jLabel7.setText("Pertanyaan");
        panel_main.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        panel_main.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 370, 100));

        jButton10.setBackground(new java.awt.Color(0, 0, 255));
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("save");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        panel_main.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, -1, -1));

        jButton11.setBackground(new java.awt.Color(0, 255, 255));
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setText("update");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        panel_main.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, -1, -1));

        jButton12.setBackground(new java.awt.Color(255, 0, 0));
        jButton12.setForeground(new java.awt.Color(255, 255, 255));
        jButton12.setText("Delete");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        panel_main.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setText("Halaman Pertanyaan");
        panel_main.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        panel_materi.setBackground(new java.awt.Color(255, 0, 51));
        panel_materi.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel_materi.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane9.setViewportView(jTable5);

        panel_materi.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 1030, 280));

        jLabel12.setText("Nama Paket");
        panel_materi.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, -1, -1));

        jTextArea5.setColumns(20);
        jTextArea5.setRows(5);
        jScrollPane10.setViewportView(jTextArea5);

        panel_materi.add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 340, 130));

        jLabel13.setText("Masukan Konten");
        panel_materi.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, -1, -1));

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        panel_materi.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 340, 40));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        panel_materi.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, 240, 40));

        jLabel15.setText("Judul");
        panel_materi.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, -1, -1));

        jButton4.setBackground(new java.awt.Color(0, 0, 255));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("save");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        panel_materi.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, -1, -1));

        jButton5.setBackground(new java.awt.Color(0, 255, 255));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("update");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        panel_materi.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, -1, -1));

        jButton6.setBackground(new java.awt.Color(255, 0, 0));
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Delete");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        panel_materi.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 370, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Halaman Materi");
        panel_materi.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        panel_paket.setBackground(new java.awt.Color(0, 204, 204));
        panel_paket.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel_paket.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabel_paket.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Nama Paket", "Deskripsi", "Foto Paket Belajar"
            }
        ));
        tabel_paket.setDragEnabled(true);
        tabel_paket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_paketMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(tabel_paket);

        panel_paket.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 1000, 300));

        jLabel4.setText("Id Paket (AI)");
        panel_paket.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, -1, -1));

        id_paket_t.setEditable(false);
        id_paket_t.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_paket_tActionPerformed(evt);
            }
        });
        panel_paket.add(id_paket_t, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 50, 40));

        save_button.setBackground(new java.awt.Color(0, 0, 255));
        save_button.setForeground(new java.awt.Color(255, 255, 255));
        save_button.setText("save");
        save_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_buttonActionPerformed(evt);
            }
        });
        panel_paket.add(save_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        update_btn_paket.setBackground(new java.awt.Color(0, 255, 255));
        update_btn_paket.setForeground(new java.awt.Color(255, 255, 255));
        update_btn_paket.setText("update");
        update_btn_paket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_btn_paketActionPerformed(evt);
            }
        });
        panel_paket.add(update_btn_paket, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, -1, -1));

        resetButton.setBackground(new java.awt.Color(153, 153, 153));
        resetButton.setForeground(new java.awt.Color(255, 255, 255));
        resetButton.setText("reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });
        panel_paket.add(resetButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 300, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("Halaman Paket Belajar");
        panel_paket.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        p_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_searchActionPerformed(evt);
            }
        });
        p_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                p_searchKeyReleased(evt);
            }
        });
        panel_paket.add(p_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 380, 230, 40));

        jLabel9.setText("Cari");
        panel_paket.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 360, -1, -1));
        panel_paket.add(nama_paket_paket1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 230, 40));

        jLabel10.setText("Deskripsi");
        panel_paket.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        deskripsi_paket.setColumns(20);
        deskripsi_paket.setRows(5);
        jScrollPane2.setViewportView(deskripsi_paket);

        panel_paket.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 380, 140));

        jLabel11.setText("Masukan Nama Paket");
        panel_paket.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        delete_paket_btn.setBackground(new java.awt.Color(255, 0, 0));
        delete_paket_btn.setForeground(new java.awt.Color(255, 255, 255));
        delete_paket_btn.setText("Delete");
        delete_paket_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_paket_btnActionPerformed(evt);
            }
        });
        panel_paket.add(delete_paket_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, -1, -1));

        upload_img_paket.setText("Upload Gambar");
        upload_img_paket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upload_img_paketActionPerformed(evt);
            }
        });
        panel_paket.add(upload_img_paket, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 290, 130, 40));

        label_image_paket.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        panel_paket.add(label_image_paket, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 500, 270));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_materi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(panel_paket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(panel_main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_materi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(panel_paket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(panel_main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 1000, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void materi_pMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_materi_pMouseClicked
        // TODO add your handling code here:
//        dispose();
//        Soal soal = new Soal(this);
//        soal.setVisible(true);
        panel_paket.setVisible(false);
        panel_materi.setVisible(true);
        panel_main.setVisible(false);

        soal1.setForeground(Color.GRAY);
        p_paket.setForeground(Color.GRAY);
        materi_p.setForeground(Color.WHITE);

    }//GEN-LAST:event_materi_pMouseClicked

    private void dashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardMouseClicked
        // TODO add your handling code here:
        dispose();
        Dashboard_Admin dashboard = new Dashboard_Admin(this, null);
        dashboard.setVisible(true);
    }//GEN-LAST:event_dashboardMouseClicked

    private void profileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileMouseClicked

    }//GEN-LAST:event_profileMouseClicked

    private void LogoutBtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutBtn1MouseClicked
        // TODO add your handling code here:
        int choice = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin logout?", "Konfirmasi Logout", JOptionPane.YES_NO_OPTION);

        if (choice == JOptionPane.YES_OPTION) {
            AdminSession.setLoggedInUser(null);

            LogingGuru loginPage = new LogingGuru(this);
            loginPage.setVisible(true);

            this.dispose();
        }
    }//GEN-LAST:event_LogoutBtn1MouseClicked

    private void soal1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_soal1MouseClicked
        // TODO add your handling code here:
        panel_paket.setVisible(false);
        panel_materi.setVisible(false);
        panel_main.setVisible(true);

        soal1.setForeground(Color.WHITE);
        p_paket.setForeground(Color.GRAY);
        materi_p.setForeground(Color.GRAY);

    }//GEN-LAST:event_soal1MouseClicked

    private void p_paketMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_paketMouseClicked
        // TODO add your handling code here:
        panel_paket.setVisible(true);
        panel_materi.setVisible(false);
        panel_main.setVisible(false);

        soal1.setForeground(Color.GRAY);
        p_paket.setForeground(Color.WHITE);
        materi_p.setForeground(Color.GRAY);
    }//GEN-LAST:event_p_paketMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void save_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_buttonActionPerformed
        // TODO add your handling code here:
        String name = nama_paket_paket1.getText();
        String deskripsi = deskripsi_paket.getText();

        try {
            InputStream image = new FileInputStream(new File(pathImgPaket));
            success = dbConnect.addPackage(name, deskripsi, image);

            if (!name.isEmpty() || !deskripsi.isEmpty()) {
                if (success) {
                    tbload();
//                JOptionPane.showMessageDialog(null, "Package added successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
                    System.out.print("berhasil");
                } else {
                    JOptionPane.showMessageDialog(null, "Kolom nama dan deskripsi haru di isi !", "Warning", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Soal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_save_buttonActionPerformed

    private void update_btn_paketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_btn_paketActionPerformed
        // TODO add your handling code here:

        //        Get the cureent of the fiel of table coy
        //        DefaultTableModel tbmodel = (DefaultTableModel) tabel_paket.getModel();
        //        if (tabel_paket.getSelectedRowCount() == 1) {
        //            int selectedRow = tabel_paket.getSelectedRow();
        //            String id = id_paket_t.getText();
        //            String name = nama_paket_paket1.getText();
        //            String deskripsi = deskripsi_paket.getText();
        //
        //            // call edit if true
        //            int packageId = Integer.parseInt(id);
        //            success = editPackage(packageId, name, deskripsi);
        //
        //            if (success) {
        //                // if its true renew data di db
        //                tbmodel.setValueAt(id, selectedRow, 0);
        //                tbmodel.setValueAt(name, selectedRow, 1);
        //                tbmodel.setValueAt(deskripsi, selectedRow, 2);
        //                JOptionPane.showMessageDialog(null, "Package updated successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
        //            } else {
        //                JOptionPane.showMessageDialog(null, "Failed to update package!", "Error", JOptionPane.ERROR_MESSAGE);
        //            }
        //        } else {
        //            JOptionPane.showMessageDialog(null, "Please select a row to update.", "Error", JOptionPane.ERROR_MESSAGE);
        //        }   
        DefaultTableModel tbmodel = (DefaultTableModel) tabel_paket.getModel();
        if (tabel_paket.getSelectedRowCount() == 1) {
            int selectedRow = tabel_paket.getSelectedRow();
            String id = id_paket_t.getText();
            String name = nama_paket_paket1.getText();
            String deskripsi = deskripsi_paket.getText();

            if (!name.isEmpty() && !deskripsi.isEmpty() && pathImgPaket != null && !pathImgPaket.isEmpty()) {
                try {
                    InputStream image = new FileInputStream(new File(pathImgPaket));
                    boolean success = dbConnect.editPackage(Integer.parseInt(id), name, deskripsi, image);

                    if (success) {
                        // Jika update berhasil, perbarui tampilan tabel
                        tbload();
                        JOptionPane.showMessageDialog(null, "Package updated successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
                    } else {
                        JOptionPane.showMessageDialog(null, "Failed to update package!", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(Soal.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null, "File not found!", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Name, description, and image must be provided!", "Warning", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please select a row to update.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_update_btn_paketActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        // TODO add your handling code here:
        nama_paket_paket1.setText("");
        deskripsi_paket.setText("");
        id_paket_t.setText("");
        label_image_paket.setIcon(null);
        label_image_paket.setText("");
    }//GEN-LAST:event_resetButtonActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void p_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_p_searchKeyReleased
        // TODO add your handling code here:

        String searchInput = p_search.getText();
        DefaultTableModel dt = (DefaultTableModel) tabel_paket.getModel();
        dt.setRowCount(0);

        try (Connection connection = dbConnect.connect()) {
            if (connection != null) {
                String query;
                PreparedStatement preparedStatement;

                try {
                    int id = Integer.parseInt(searchInput);
                    // Jika bisa, gunakan klausa id = ?
                    query = "SELECT * FROM packages WHERE id = ?";
                    preparedStatement = connection.prepareStatement(query);
                    preparedStatement.setInt(1, id);
                } catch (NumberFormatException e) {
                    // Jika tidak bisa, gunakan klausa name LIKE ? dan deskripsi LIKE ?
                    query = "SELECT * FROM packages WHERE name LIKE ? OR deskripsi LIKE ?";
                    preparedStatement = connection.prepareStatement(query);
                    preparedStatement.setString(1, "%" + searchInput + "%");
                    preparedStatement.setString(2, "%" + searchInput + "%");
                }

                ResultSet rs = preparedStatement.executeQuery();

                while (rs.next()) {
                    Vector v = new Vector();
                    v.add(rs.getString(1));
                    v.add(rs.getString(2));
                    v.add(rs.getString(3));

                    dt.addRow(v);
                }
            }

        } catch (SQLException e) {
            dbConnect.logger.log(Level.SEVERE, "Database connection error", e);
        }
    }//GEN-LAST:event_p_searchKeyReleased

    private void tabel_paketMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_paketMouseClicked
        // TODO add your handling code here:
        if (tabel_paket.getSelectedRow() != -1) {
            int i = tabel_paket.getSelectedRow();
            String id = tabel_paket.getValueAt(i, 0).toString();
            String name = tabel_paket.getValueAt(i, 1).toString();
            String deskripsi = tabel_paket.getValueAt(i, 2).toString();

            id_paket_t.setText(id);
            nama_paket_paket1.setText(name);
            deskripsi_paket.setText(deskripsi);

            // Ambil path gambar dari rowData di kolom keempat (indeks kolom 3)
            String imagePath = tabel_paket.getValueAt(i, 3).toString();

            if (imagePath != null && !imagePath.isEmpty()) {
                File imgFile = new File(imagePath);
                if (imgFile.exists()) {
                    try {
                        // Baca gambar dari file
                        BufferedImage bufi = ImageIO.read(imgFile);

                        // Dapatkan dimensi label
                        int labelWidth = label_image_paket.getWidth();
                        int labelHeight = label_image_paket.getHeight();

                        // Ubah ukuran gambar sesuai dengan dimensi label
                        Image img = bufi.getScaledInstance(labelWidth, labelHeight, Image.SCALE_SMOOTH);
                        ImageIcon icon = new ImageIcon(img);

                        // Set ImageIcon ke label_image_paket
                        label_image_paket.setIcon(icon);
                        label_image_paket.setText("");  // Hapus teks dari label jika ada gambar
                    } catch (IOException e) {
                        e.printStackTrace();
                        System.out.println("Error: Gambar tidak dapat dibaca.");
                        label_image_paket.setIcon(null);
                        label_image_paket.setText("Gambar tidak dapat dibaca.");
                    }
                } else {
                    // Jika file gambar tidak ada
                    label_image_paket.setIcon(null);
                    label_image_paket.setText("Tidak ada gambar di upload.");
                }
            } else {
                // Jika path gambar null atau kosong, hapus ikon dari label dan set teks
                label_image_paket.setIcon(null);
                label_image_paket.setText("Tidak ada gambar tersedia.");
            }
        } else {
            System.out.print("Error: Tidak ada baris yang dipilih.");
        }
    }//GEN-LAST:event_tabel_paketMouseClicked

    private void p_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p_searchActionPerformed

    private void delete_paket_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_paket_btnActionPerformed
        // TODO add your handling code here:

//        DefaultTableModel tbmodel = (DefaultTableModel) tabel_paket.getModel();
//        if (tabel_paket.getSelectedRowCount() == 1) {
//            int selectedRow = tabel_paket.getSelectedRow();
//            String id = tbmodel.getValueAt(selectedRow, 0).toString();
//            String name = tbmodel.getValueAt(selectedRow, 1).toString();
//
//            // confirmation delete
//            int response = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this package " + name + " ? ", "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
//            if (response == JOptionPane.YES_OPTION) {
//                // class the func from db connect
//                int packageId = Integer.parseInt(id);
//                success = deletePackage(packageId);
//
//                if (success) {
//                    // if delete success delte from DB
//                    tbmodel.removeRow(selectedRow);
//                    JOptionPane.showMessageDialog(null, "Package deleted successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
//                } else {
//                    JOptionPane.showMessageDialog(null, "Failed to delete package!", "Error", JOptionPane.ERROR_MESSAGE);
//                }
//            }
//        } else {
//            JOptionPane.showMessageDialog(null, "Please select a row to delete.", "Error", JOptionPane.ERROR_MESSAGE);
//        }
        DefaultTableModel tbmodel = (DefaultTableModel) tabel_paket.getModel();
        if (tabel_paket.getSelectedRowCount() == 1) {
            int selectedRow = tabel_paket.getSelectedRow();
            String id = tbmodel.getValueAt(selectedRow, 0).toString();
            String name = tbmodel.getValueAt(selectedRow, 1).toString();

            // Konfirmasi penghapusan
            int response = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this package " + name + " ? ", "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (response == JOptionPane.YES_OPTION) {
                // Panggil fungsi deletePackage dari dbConnect
                int packageId = Integer.parseInt(id);
                success = dbConnect.deletePackage(packageId);

                if (success) {
                    // Jika penghapusan berhasil, hapus juga baris dari tabel
                    tbmodel.removeRow(selectedRow);
                    JOptionPane.showMessageDialog(null, "Package deleted successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(null, "Failed to delete package!", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please select a row to delete.", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_delete_paket_btnActionPerformed

    private void upload_img_paketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upload_img_paketActionPerformed
        // TODO add your handling code here:
        JFileChooser image = new JFileChooser();
        image.showOpenDialog(null);

        File file = image.getSelectedFile();
        String path = file.getAbsolutePath();
        try {
            BufferedImage bufi = ImageIO.read(new File(path));
            Image img = bufi.getScaledInstance(500, 270, Image.SCALE_SMOOTH);
            ImageIcon icon = new ImageIcon(img);
            label_image_paket.setIcon(icon);

            pathImgPaket = path;
        } catch (IOException ex) {
            Logger.getLogger(Soal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_upload_img_paketActionPerformed

    private void id_paket_tActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_paket_tActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_paket_tActionPerformed

    /**
     * @param args the command line arguments
     */
    //    public static void main(String args[]) {
    //        /* Set the Nimbus look and feel */
    //        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    //        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
    //         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
    //         */
    //        try {
    //            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
    //                if ("Nimbus".equals(info.getName())) {
    //                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
    //                    break;
    //                }
    //            }
    //        } catch (ClassNotFoundException ex) {
    //            java.util.logging.Logger.getLogger(Soal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    //        } catch (InstantiationException ex) {
    //            java.util.logging.Logger.getLogger(Soal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    //        } catch (IllegalAccessException ex) {
    //            java.util.logging.Logger.getLogger(Soal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    //        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
    //            java.util.logging.Logger.getLogger(Soal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    //        }
    //        //</editor-fold>
    //
    //        /* Create and display the form */
    //        java.awt.EventQueue.invokeLater(new Runnable() {
    //            public void run() {
    //                new Soal().setVisible(true);
    //            }
    //        });
    //    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LogoutBtn1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel dashboard;
    private javax.swing.JButton delete_paket_btn;
    private javax.swing.JTextArea deskripsi_paket;
    private javax.swing.JTextField id_paket_t;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable5;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JLabel label_image_paket;
    private javax.swing.JLabel materi_p;
    private javax.swing.JTextField nama_paket_paket1;
    private javax.swing.JLabel p_paket;
    private javax.swing.JTextField p_search;
    private javax.swing.JPanel panel_main;
    private javax.swing.JPanel panel_materi;
    private javax.swing.JPanel panel_paket;
    private javax.swing.JLabel profile;
    private javax.swing.JButton resetButton;
    private javax.swing.JButton save_button;
    private javax.swing.JLabel soal1;
    private javax.swing.JTable tabel_paket;
    private javax.swing.JButton update_btn_paket;
    private javax.swing.JButton upload_img_paket;
    // End of variables declaration//GEN-END:variables
}
